title: Welcome To My Space
author: iMubGit
email: imubmail@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey I am Mubarak A.L, I love Web development, Infosecurity, Cybersesurity and Crypto and Marketing.
# social links
twitter_username: iMubSpace # DO NOT include the @ character, or else the build will fail!
github_username:  iMubGit # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
